### ISSUE TITLE
Wrapping a function with `LogDensityProblem`

### ISSUE THREAD

**Issue by xukai92** [tpapp/LogDensityProblems.jl#10]
Is there an easy way to wrap a function with `LogDensityProblem` so that I can run it with `DynamicHMC.NUTS_init`?

**Comment by tpapp** [comment]
Yes, `LogDensityProblems.TransformedBayesianProblem` (will be renamed soon). Note that you appear to be using the `master` branch of `DynamicHMC`, which is a moving target, better watch all related repos as the API is currently being reorganized.

**Comment by tpapp** [comment]
It has been renamed again to `TransformedLogDensity`.

Examples etc should be updated within a few days, pending registry merges.

**Comment by tpapp** [comment]
[Examples](https://github.com/tpapp/DynamicHMCExamples.jl/) have been updated and should be informative about this; closing the issue.
