### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by torfjelde** [tpapp/LogDensityProblems.jl#109]
It would be quite useful for this project to have a way to cite it to give credit where credit is due:)

@tpapp

**Comment by tpapp** [comment]
Thanks for raising this. Happy to do something, what's the current best practice? Zenodo?

**Comment by torfjelde** [comment]
My best guess would be Zenodo yeah, though I must admit I'm also not an expert on this :grimacing:

**Comment by tpapp** [comment]
Thanks, a Zenodo badge is now in the README.

**Comment by torfjelde** [comment]
Lovely; thank you @tpapp :)
