### ISSUE TITLE
LogDensityProblems v1.0 release?

### ISSUE THREAD

**Issue by oschulz** [tpapp/LogDensityProblems.jl#48]
Would you consider a v1.0 release in the near future (from what I understand, the API of LogDensityProblems is already pretty stable)?

**Comment by tpapp** [comment]
I will wait 1 month to let people (and myself) comment on whether they need anything else in the API, then I will release 1.0.

**Comment by oschulz** [comment]
Thanks!

**Comment by tpapp** [comment]
Sorry for not following up on this. I still have some issues I want to clean up, specifically #56, before making an 1.0 release, but I am working on it.

**Comment by oschulz** [comment]
No worries - we released a BAT.jl v1.0 to have something stable, but we're actually planning to have a v2.0 with quite a few API changes in spring. I'll certainly check how I can best integrate with LogDensityProblems.
