### ISSUE TITLE
Broken links in README?

### ISSUE THREAD

**Issue by DilumAluthge** [tpapp/LogDensityProblems.jl#62]
The following links in the README are broken:
- "The `logdensity` method"
- "The `ADgradient` which"
- "The wrapper `TransformedLogDensity`"

Clicking on any of those links brings me to https://github.com/tpapp/LogDensityProblems.jl/blob/master/@ref, which gives 404 not found.

**Comment by tpapp** [comment]
Thanks, fixed by 4b9dd0c.
