### ISSUE TITLE
Documentation is not being built correctly?

### ISSUE THREAD

**Issue by DilumAluthge** [tpapp/LogDensityProblems.jl#63]
Here are three screenshots of https://tamaspapp.eu/LogDensityProblems.jl/dev/

As you can see from the various errors, it seems that maybe the documentation is not being built correctly?

---

Screenshot 1:

<img width="751" alt="Screen Shot 2020-03-27 at 02 28 00" src="https://user-images.githubusercontent.com/5619885/77728374-46dfd900-6ff4-11ea-9659-6c7e4698b664.png">

---

Screenshot 2:

<img width="753" alt="Screen Shot 2020-03-27 at 02 28 08" src="https://user-images.githubusercontent.com/5619885/77728394-50694100-6ff4-11ea-8169-7caab7ec767f.png">

---

Screenshot 3:

<img width="744" alt="Screen Shot 2020-03-27 at 02 28 59" src="https://user-images.githubusercontent.com/5619885/77728403-56f7b880-6ff4-11ea-8e0a-fe4f9f8c8a37.png">

**Comment by tpapp** [comment]
Thanks for reporting, this should be fixed now.

**Comment by DilumAluthge** [comment]
Just FYI, I still see some errors.

**Comment by tpapp** [comment]
Thanks, hopefully they are fixed now.
