### ISSUE TITLE
Analogue of this package for variational Bayes?

### ISSUE THREAD

**Issue by DilumAluthge** [tpapp/LogDensityProblems.jl#68]
I really like the approach of this package: code the log posterior density, and then sample from it using HMC.

@tpapp Are you aware of any Julia packages that use a similar approach for variational Bayes? i.e. code the log posterior density, and then approximate it using variational Bayes?

**Comment by tpapp** [comment]
I am not aware of anything, but I would be happy to support whatever is required in LogDensityProblems (so I transferred the issue here).

**Comment by tpapp** [comment]
Closing this as unrelated to this package.
