### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by andreasnoack** [tpapp/LogDensityProblems.jl#80]
It's currently not possible to run the TransformVariables tests because there is no released version of LogDensityProblems compatible with TransformVariables@0.6

**Comment by tpapp** [comment]
Thanks, I initiated registration in https://github.com/tpapp/LogDensityProblems.jl/commit/7d747e87ff93006ee58686712c9914f8ac11a96d and will close this issue as soon as it completes.

**Comment by tpapp** [comment]
Done, thanks for the reminder.
