### ISSUE TITLE
Enzyme.jl support?

### ISSUE THREAD

**Issue by robsmith11** [tpapp/LogDensityProblems.jl#83]
With a few models that have more than 100 parameters, I'm getting much faster (5-100x) log likelihood gradients with Enyzme's reverse mode when compared to ReverseDiff.jl and Zygote.jl (and ForwardDiff.jl).

Is it simple and desirable to add it to DynamicHMC.jl?

**Comment by tpapp** [comment]
I looked at the Enzyme docs and only have a vague idea on how to get both the value and the gradient (`Duplicated`?) so I will leave this to those who are more familiar with its API. Nevertheless, doing this could be as simple as 10-20 lines, see eg the [Zygote.jl wrapper](https://github.com/tpapp/LogDensityProblems.jl/blob/master/src/AD_Zygote.jl).

**Comment by vchuravy** [comment]
Cc: @wsmoses and you probably want either proper [split mode](https://github.com/EnzymeAD/Enzyme.jl/pull/334)  or at least https://github.com/EnzymeAD/Enzyme.jl/issues/107, and [ideally custom rules](https://github.com/EnzymeAD/Enzyme.jl/issues/172).
